name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 0.9.10
homepage: https://github.com/brianegan/chewie

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.9.1 <2.0.0"

dependencies:
  open_iconic_flutter: ">=0.3.0 <0.4.0"
  video_player: ">=0.7.0 <0.11.0"
  wakelock: ">=0.1.2 <0.2.0"

  flutter_mdns_plugin:
    git: https://github.com/terrabythia/flutter_mdns_plugin.git
  observable: any
  dart_chromecast:
    git: https://github.com/terrabythia/dart_chromecast.git

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
